---
title: "Homework2"
author: "Prakhar Mishra"
date: "October 2, 2019"
output: html_document
---

```{r setup, include=FALSE}

require(rgdal)
require(leaflet)
require(leaflet.extras)

require(dplyr)
require(readxl)
require(stringr)

```


```{r}
nyc_facilities <- readOGR("C:/Users/prakh/Documents/GitHub/Homework2-prakharm/Facilities Database - Shapefile.geojson")
```

#Using lines to map NYC's bicycle routes features
```{r}
bike_routes <- readOGR("C:/Users/prakh/Documents/GitHub/Homework2-prakharm/Bicycle Routes.geojson")

plot(bike_routes)

leaflet() %>%
  addTiles() %>%
  addPolylines(data = bike_routes)
```

#Using polygons to plot NYC's school zones for the 2019-2020 School Year

```{r}
school_zones <- readOGR("C:/Users/prakh/Documents/GitHub/Homework2-prakharm/2019-2020 School Zones (Middle School).geojson")

plot(school_zones)

leaflet() %>%
  addTiles() %>%
  addPolygons(data = school_zones)
```


```{r}
parking_meter <-read.csv("C:/Users/prakh/Documents/GitHub/Homework2-prakharm/dot_MUNIMETER_20191001.csv")

#designing a custom palette
pallete <- colorFactor(c("#3a981a","#98271a","#271a98","#98901a","#981a98"), c("Inactive", "Active","Retired","Planned","Removed"))

#plotting the map
leaflet() %>%
  addProviderTiles("OpenStreetMap.HOT") %>%
  addCircleMarkers(data = parking_meter, lng = ~LONG, lat = ~LAT, radius = 1.5, color = ~pallete(Status)) %>%
  addLegend(position = "topright" , pal = pallete, values = parking_meter$Status, title = "Status")


```


```{r}
outline <- parking_meter[chull(parking_meter$LONG,parking_meter$LAT),]

multi_layer_map <- leaflet(parking_meter) %>%
       # Base groups
      addTiles(group = "OSM") %>%
      addProviderTiles(providers$Stamen.Toner, group = "Toner") %>%
      addProviderTiles(providers$Stamen.Watercolor, group = "Watercolor") %>%
      addProviderTiles(providers$Stamen.Terrain, group = "Terrain") %>%
      # Overlay groups
      addCircleMarkers(data = parking_meter, lng = ~LONG, lat = ~LAT, radius = 1.5, color = ~pallete(Status),group = "Parking Meters") %>%
  addLegend(position = "topright" , pal = pallete, values = parking_meter$Status, title = "Status") %>%
      addPolygons(data = outline, lng = ~LONG, lat = ~LAT,
      fill = F, weight = 2, color = "#0c17eb", group = "City Outline") %>%
      # Layers control
      addLayersControl(
     baseGroups = c("MtbMAP", "Toner", "Topography","Terrain"),
     overlayGroups = c("Parking Meters", "City Outline"),
     options = layersControlOptions(collapsed = FALSE)
  )

multi_layer_map
```

